version: "3.7"

services:

  pg_db:
    image: postgres:13.4
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=blog_java
    ports:
      - "5432:5432"
    volumes:
      - ./pg_db:/var/lib/postgresql/data/
    container_name: pr_pg